// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dashboard.proto

// Package dashboard exposes a backend server over gRPC

package dashboard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TdType int32

const (
	TdType_TDTYPE_TEXT              TdType = 0
	TdType_TDTYPE_BADGE             TdType = 1
	TdType_TDTYPE_BOOL              TdType = 2
	TdType_TDTYPE_IMG               TdType = 3
	TdType_TDTYPE_LINK              TdType = 4
	TdType_TDTYPE_AVATAR            TdType = 5
	TdType_TDTYPE_IMG_TEXT          TdType = 6
	TdType_TDTYPE_IMG_TITLE_CONTENT TdType = 7
)

var TdType_name = map[int32]string{
	0: "TDTYPE_TEXT",
	1: "TDTYPE_BADGE",
	2: "TDTYPE_BOOL",
	3: "TDTYPE_IMG",
	4: "TDTYPE_LINK",
	5: "TDTYPE_AVATAR",
	6: "TDTYPE_IMG_TEXT",
	7: "TDTYPE_IMG_TITLE_CONTENT",
}

var TdType_value = map[string]int32{
	"TDTYPE_TEXT":              0,
	"TDTYPE_BADGE":             1,
	"TDTYPE_BOOL":              2,
	"TDTYPE_IMG":               3,
	"TDTYPE_LINK":              4,
	"TDTYPE_AVATAR":            5,
	"TDTYPE_IMG_TEXT":          6,
	"TDTYPE_IMG_TITLE_CONTENT": 7,
}

func (x TdType) String() string {
	return proto.EnumName(TdType_name, int32(x))
}

func (TdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{0}
}

// 颜色类型
type ColorType int32

const (
	ColorType_COLORTYPE_NONE           ColorType = 0
	ColorType_COLORTYPE_GREEN_SUCCESS  ColorType = 1
	ColorType_COLORTYPE_BLUE_PRIMARY   ColorType = 2
	ColorType_COLORTYPE_RED_DANGER     ColorType = 3
	ColorType_COLORTYPE_YELLOW_WARNING ColorType = 4
	ColorType_COLORTYPE_CYAN_INFO      ColorType = 5
	ColorType_COLORTYPE_GRAY_SECONDARY ColorType = 6
	ColorType_COLORTYPE_RANDOM         ColorType = 7
)

var ColorType_name = map[int32]string{
	0: "COLORTYPE_NONE",
	1: "COLORTYPE_GREEN_SUCCESS",
	2: "COLORTYPE_BLUE_PRIMARY",
	3: "COLORTYPE_RED_DANGER",
	4: "COLORTYPE_YELLOW_WARNING",
	5: "COLORTYPE_CYAN_INFO",
	6: "COLORTYPE_GRAY_SECONDARY",
	7: "COLORTYPE_RANDOM",
}

var ColorType_value = map[string]int32{
	"COLORTYPE_NONE":           0,
	"COLORTYPE_GREEN_SUCCESS":  1,
	"COLORTYPE_BLUE_PRIMARY":   2,
	"COLORTYPE_RED_DANGER":     3,
	"COLORTYPE_YELLOW_WARNING": 4,
	"COLORTYPE_CYAN_INFO":      5,
	"COLORTYPE_GRAY_SECONDARY": 6,
	"COLORTYPE_RANDOM":         7,
}

func (x ColorType) String() string {
	return proto.EnumName(ColorType_name, int32(x))
}

func (ColorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{1}
}

type ChartType int32

const (
	ChartType_CHARTTYPE_LINE ChartType = 0
	ChartType_CHARTTYPE_BAR  ChartType = 1
	ChartType_CHARTTYPE_PIE  ChartType = 2
)

var ChartType_name = map[int32]string{
	0: "CHARTTYPE_LINE",
	1: "CHARTTYPE_BAR",
	2: "CHARTTYPE_PIE",
}

var ChartType_value = map[string]int32{
	"CHARTTYPE_LINE": 0,
	"CHARTTYPE_BAR":  1,
	"CHARTTYPE_PIE":  2,
}

func (x ChartType) String() string {
	return proto.EnumName(ChartType_name, int32(x))
}

func (ChartType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{2}
}

type Hello struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{0}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Pong struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type SidebarMenu struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FaIcon               string          `protobuf:"bytes,2,opt,name=fa_icon,json=faIcon,proto3" json:"fa_icon,omitempty"`
	Text                 string          `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Groups               []*SidebarGroup `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SidebarMenu) Reset()         { *m = SidebarMenu{} }
func (m *SidebarMenu) String() string { return proto.CompactTextString(m) }
func (*SidebarMenu) ProtoMessage()    {}
func (*SidebarMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{2}
}

func (m *SidebarMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SidebarMenu.Unmarshal(m, b)
}
func (m *SidebarMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SidebarMenu.Marshal(b, m, deterministic)
}
func (m *SidebarMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidebarMenu.Merge(m, src)
}
func (m *SidebarMenu) XXX_Size() int {
	return xxx_messageInfo_SidebarMenu.Size(m)
}
func (m *SidebarMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_SidebarMenu.DiscardUnknown(m)
}

var xxx_messageInfo_SidebarMenu proto.InternalMessageInfo

func (m *SidebarMenu) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SidebarMenu) GetFaIcon() string {
	if m != nil {
		return m.FaIcon
	}
	return ""
}

func (m *SidebarMenu) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SidebarMenu) GetGroups() []*SidebarGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

type SidebarGroup struct {
	Text                 string          `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Items                []*SidebarEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SidebarGroup) Reset()         { *m = SidebarGroup{} }
func (m *SidebarGroup) String() string { return proto.CompactTextString(m) }
func (*SidebarGroup) ProtoMessage()    {}
func (*SidebarGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{3}
}

func (m *SidebarGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SidebarGroup.Unmarshal(m, b)
}
func (m *SidebarGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SidebarGroup.Marshal(b, m, deterministic)
}
func (m *SidebarGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidebarGroup.Merge(m, src)
}
func (m *SidebarGroup) XXX_Size() int {
	return xxx_messageInfo_SidebarGroup.Size(m)
}
func (m *SidebarGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SidebarGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SidebarGroup proto.InternalMessageInfo

func (m *SidebarGroup) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SidebarGroup) GetItems() []*SidebarEntry {
	if m != nil {
		return m.Items
	}
	return nil
}

type SidebarEntry struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Route                string   `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SidebarEntry) Reset()         { *m = SidebarEntry{} }
func (m *SidebarEntry) String() string { return proto.CompactTextString(m) }
func (*SidebarEntry) ProtoMessage()    {}
func (*SidebarEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{4}
}

func (m *SidebarEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SidebarEntry.Unmarshal(m, b)
}
func (m *SidebarEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SidebarEntry.Marshal(b, m, deterministic)
}
func (m *SidebarEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidebarEntry.Merge(m, src)
}
func (m *SidebarEntry) XXX_Size() int {
	return xxx_messageInfo_SidebarEntry.Size(m)
}
func (m *SidebarEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SidebarEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SidebarEntry proto.InternalMessageInfo

func (m *SidebarEntry) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SidebarEntry) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

type GetSidebarMenusReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSidebarMenusReq) Reset()         { *m = GetSidebarMenusReq{} }
func (m *GetSidebarMenusReq) String() string { return proto.CompactTextString(m) }
func (*GetSidebarMenusReq) ProtoMessage()    {}
func (*GetSidebarMenusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{5}
}

func (m *GetSidebarMenusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSidebarMenusReq.Unmarshal(m, b)
}
func (m *GetSidebarMenusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSidebarMenusReq.Marshal(b, m, deterministic)
}
func (m *GetSidebarMenusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSidebarMenusReq.Merge(m, src)
}
func (m *GetSidebarMenusReq) XXX_Size() int {
	return xxx_messageInfo_GetSidebarMenusReq.Size(m)
}
func (m *GetSidebarMenusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSidebarMenusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSidebarMenusReq proto.InternalMessageInfo

type GetSidebarMenusRes struct {
	Menus                []*SidebarMenu `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetSidebarMenusRes) Reset()         { *m = GetSidebarMenusRes{} }
func (m *GetSidebarMenusRes) String() string { return proto.CompactTextString(m) }
func (*GetSidebarMenusRes) ProtoMessage()    {}
func (*GetSidebarMenusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{6}
}

func (m *GetSidebarMenusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSidebarMenusRes.Unmarshal(m, b)
}
func (m *GetSidebarMenusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSidebarMenusRes.Marshal(b, m, deterministic)
}
func (m *GetSidebarMenusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSidebarMenusRes.Merge(m, src)
}
func (m *GetSidebarMenusRes) XXX_Size() int {
	return xxx_messageInfo_GetSidebarMenusRes.Size(m)
}
func (m *GetSidebarMenusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSidebarMenusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetSidebarMenusRes proto.InternalMessageInfo

func (m *GetSidebarMenusRes) GetMenus() []*SidebarMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

type Result struct {
	Errcode              int64    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{7}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *Result) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type YsadminReq struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Expand               string   `protobuf:"bytes,6,opt,name=expand,proto3" json:"expand,omitempty"`
	Token                string   `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	Sname                string   `protobuf:"bytes,8,opt,name=sname,proto3" json:"sname,omitempty"`
	Cid                  string   `protobuf:"bytes,9,opt,name=cid,proto3" json:"cid,omitempty"`
	Month                string   `protobuf:"bytes,10,opt,name=month,proto3" json:"month,omitempty"`
	Week                 string   `protobuf:"bytes,11,opt,name=week,proto3" json:"week,omitempty"`
	Page                 int32    `protobuf:"varint,12,opt,name=page,proto3" json:"page,omitempty"`
	Region               string   `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Country              string   `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	Area                 string   `protobuf:"bytes,15,opt,name=area,proto3" json:"area,omitempty"`
	ClickValue           string   `protobuf:"bytes,20,opt,name=click_value,json=clickValue,proto3" json:"click_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YsadminReq) Reset()         { *m = YsadminReq{} }
func (m *YsadminReq) String() string { return proto.CompactTextString(m) }
func (*YsadminReq) ProtoMessage()    {}
func (*YsadminReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{8}
}

func (m *YsadminReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YsadminReq.Unmarshal(m, b)
}
func (m *YsadminReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YsadminReq.Marshal(b, m, deterministic)
}
func (m *YsadminReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YsadminReq.Merge(m, src)
}
func (m *YsadminReq) XXX_Size() int {
	return xxx_messageInfo_YsadminReq.Size(m)
}
func (m *YsadminReq) XXX_DiscardUnknown() {
	xxx_messageInfo_YsadminReq.DiscardUnknown(m)
}

var xxx_messageInfo_YsadminReq proto.InternalMessageInfo

func (m *YsadminReq) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *YsadminReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *YsadminReq) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *YsadminReq) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *YsadminReq) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *YsadminReq) GetExpand() string {
	if m != nil {
		return m.Expand
	}
	return ""
}

func (m *YsadminReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *YsadminReq) GetSname() string {
	if m != nil {
		return m.Sname
	}
	return ""
}

func (m *YsadminReq) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *YsadminReq) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *YsadminReq) GetWeek() string {
	if m != nil {
		return m.Week
	}
	return ""
}

func (m *YsadminReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *YsadminReq) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *YsadminReq) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *YsadminReq) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *YsadminReq) GetClickValue() string {
	if m != nil {
		return m.ClickValue
	}
	return ""
}

type QueryReq struct {
	Package              string      `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Endpoint             string      `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Environment          string      `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	GatewayCode          string      `protobuf:"bytes,4,opt,name=gateway_code,json=gatewayCode,proto3" json:"gateway_code,omitempty"`
	YsadminReq           *YsadminReq `protobuf:"bytes,5,opt,name=ysadmin_req,json=ysadminReq,proto3" json:"ysadmin_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{9}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *QueryReq) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *QueryReq) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *QueryReq) GetGatewayCode() string {
	if m != nil {
		return m.GatewayCode
	}
	return ""
}

func (m *QueryReq) GetYsadminReq() *YsadminReq {
	if m != nil {
		return m.YsadminReq
	}
	return nil
}

type QueryRes struct {
	Result               *Result      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Tables               []*TableInfo `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	Charts               []*ChartInfo `protobuf:"bytes,3,rep,name=charts,proto3" json:"charts,omitempty"`
	Page                 int32        `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryRes) Reset()         { *m = QueryRes{} }
func (m *QueryRes) String() string { return proto.CompactTextString(m) }
func (*QueryRes) ProtoMessage()    {}
func (*QueryRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{10}
}

func (m *QueryRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRes.Unmarshal(m, b)
}
func (m *QueryRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRes.Marshal(b, m, deterministic)
}
func (m *QueryRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRes.Merge(m, src)
}
func (m *QueryRes) XXX_Size() int {
	return xxx_messageInfo_QueryRes.Size(m)
}
func (m *QueryRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRes proto.InternalMessageInfo

func (m *QueryRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *QueryRes) GetTables() []*TableInfo {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *QueryRes) GetCharts() []*ChartInfo {
	if m != nil {
		return m.Charts
	}
	return nil
}

func (m *QueryRes) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CommitReq struct {
	Package              string      `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Endpoint             string      `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Req                  *YsadminReq `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CommitReq) Reset()         { *m = CommitReq{} }
func (m *CommitReq) String() string { return proto.CompactTextString(m) }
func (*CommitReq) ProtoMessage()    {}
func (*CommitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{11}
}

func (m *CommitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReq.Unmarshal(m, b)
}
func (m *CommitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReq.Marshal(b, m, deterministic)
}
func (m *CommitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReq.Merge(m, src)
}
func (m *CommitReq) XXX_Size() int {
	return xxx_messageInfo_CommitReq.Size(m)
}
func (m *CommitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReq proto.InternalMessageInfo

func (m *CommitReq) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *CommitReq) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *CommitReq) GetReq() *YsadminReq {
	if m != nil {
		return m.Req
	}
	return nil
}

type CommitRes struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRes) Reset()         { *m = CommitRes{} }
func (m *CommitRes) String() string { return proto.CompactTextString(m) }
func (*CommitRes) ProtoMessage()    {}
func (*CommitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{12}
}

func (m *CommitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRes.Unmarshal(m, b)
}
func (m *CommitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRes.Marshal(b, m, deterministic)
}
func (m *CommitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRes.Merge(m, src)
}
func (m *CommitRes) XXX_Size() int {
	return xxx_messageInfo_CommitRes.Size(m)
}
func (m *CommitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRes.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRes proto.InternalMessageInfo

func (m *CommitRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type TdInfo struct {
	TdType               TdType    `protobuf:"varint,1,opt,name=td_type,json=tdType,proto3,enum=dashboard.TdType" json:"td_type,omitempty"`
	Content              string    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsTrue               bool      `protobuf:"varint,3,opt,name=is_true,json=isTrue,proto3" json:"is_true,omitempty"`
	Link                 string    `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Color                ColorType `protobuf:"varint,5,opt,name=color,proto3,enum=dashboard.ColorType" json:"color,omitempty"`
	Width                int32     `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32     `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Title                string    `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Clickable            bool      `protobuf:"varint,9,opt,name=clickable,proto3" json:"clickable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TdInfo) Reset()         { *m = TdInfo{} }
func (m *TdInfo) String() string { return proto.CompactTextString(m) }
func (*TdInfo) ProtoMessage()    {}
func (*TdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{13}
}

func (m *TdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TdInfo.Unmarshal(m, b)
}
func (m *TdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TdInfo.Marshal(b, m, deterministic)
}
func (m *TdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TdInfo.Merge(m, src)
}
func (m *TdInfo) XXX_Size() int {
	return xxx_messageInfo_TdInfo.Size(m)
}
func (m *TdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TdInfo proto.InternalMessageInfo

func (m *TdInfo) GetTdType() TdType {
	if m != nil {
		return m.TdType
	}
	return TdType_TDTYPE_TEXT
}

func (m *TdInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TdInfo) GetIsTrue() bool {
	if m != nil {
		return m.IsTrue
	}
	return false
}

func (m *TdInfo) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *TdInfo) GetColor() ColorType {
	if m != nil {
		return m.Color
	}
	return ColorType_COLORTYPE_NONE
}

func (m *TdInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *TdInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TdInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TdInfo) GetClickable() bool {
	if m != nil {
		return m.Clickable
	}
	return false
}

type TdRow struct {
	Infos                []*TdInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TdRow) Reset()         { *m = TdRow{} }
func (m *TdRow) String() string { return proto.CompactTextString(m) }
func (*TdRow) ProtoMessage()    {}
func (*TdRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{14}
}

func (m *TdRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TdRow.Unmarshal(m, b)
}
func (m *TdRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TdRow.Marshal(b, m, deterministic)
}
func (m *TdRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TdRow.Merge(m, src)
}
func (m *TdRow) XXX_Size() int {
	return xxx_messageInfo_TdRow.Size(m)
}
func (m *TdRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TdRow.DiscardUnknown(m)
}

var xxx_messageInfo_TdRow proto.InternalMessageInfo

func (m *TdRow) GetInfos() []*TdInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type TableInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ths                  []string `protobuf:"bytes,2,rep,name=ths,proto3" json:"ths,omitempty"`
	Rows                 []*TdRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableInfo) Reset()         { *m = TableInfo{} }
func (m *TableInfo) String() string { return proto.CompactTextString(m) }
func (*TableInfo) ProtoMessage()    {}
func (*TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{15}
}

func (m *TableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableInfo.Unmarshal(m, b)
}
func (m *TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableInfo.Marshal(b, m, deterministic)
}
func (m *TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableInfo.Merge(m, src)
}
func (m *TableInfo) XXX_Size() int {
	return xxx_messageInfo_TableInfo.Size(m)
}
func (m *TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TableInfo proto.InternalMessageInfo

func (m *TableInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TableInfo) GetThs() []string {
	if m != nil {
		return m.Ths
	}
	return nil
}

func (m *TableInfo) GetRows() []*TdRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ChartInfo struct {
	ChartType            ChartType  `protobuf:"varint,1,opt,name=chart_type,json=chartType,proto3,enum=dashboard.ChartType" json:"chart_type,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               []string   `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Datasets             []*Dataset `protobuf:"bytes,4,rep,name=datasets,proto3" json:"datasets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChartInfo) Reset()         { *m = ChartInfo{} }
func (m *ChartInfo) String() string { return proto.CompactTextString(m) }
func (*ChartInfo) ProtoMessage()    {}
func (*ChartInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{16}
}

func (m *ChartInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartInfo.Unmarshal(m, b)
}
func (m *ChartInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartInfo.Marshal(b, m, deterministic)
}
func (m *ChartInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartInfo.Merge(m, src)
}
func (m *ChartInfo) XXX_Size() int {
	return xxx_messageInfo_ChartInfo.Size(m)
}
func (m *ChartInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChartInfo proto.InternalMessageInfo

func (m *ChartInfo) GetChartType() ChartType {
	if m != nil {
		return m.ChartType
	}
	return ChartType_CHARTTYPE_LINE
}

func (m *ChartInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChartInfo) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ChartInfo) GetDatasets() []*Dataset {
	if m != nil {
		return m.Datasets
	}
	return nil
}

type Dataset struct {
	Label                string      `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Color                ColorType   `protobuf:"varint,2,opt,name=color,proto3,enum=dashboard.ColorType" json:"color,omitempty"`
	Datas                []int64     `protobuf:"varint,3,rep,packed,name=datas,proto3" json:"datas,omitempty"`
	Colors               []ColorType `protobuf:"varint,4,rep,packed,name=colors,proto3,enum=dashboard.ColorType" json:"colors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{17}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Dataset) GetColor() ColorType {
	if m != nil {
		return m.Color
	}
	return ColorType_COLORTYPE_NONE
}

func (m *Dataset) GetDatas() []int64 {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *Dataset) GetColors() []ColorType {
	if m != nil {
		return m.Colors
	}
	return nil
}

func init() {
	proto.RegisterEnum("dashboard.TdType", TdType_name, TdType_value)
	proto.RegisterEnum("dashboard.ColorType", ColorType_name, ColorType_value)
	proto.RegisterEnum("dashboard.ChartType", ChartType_name, ChartType_value)
	proto.RegisterType((*Hello)(nil), "dashboard.Hello")
	proto.RegisterType((*Pong)(nil), "dashboard.Pong")
	proto.RegisterType((*SidebarMenu)(nil), "dashboard.SidebarMenu")
	proto.RegisterType((*SidebarGroup)(nil), "dashboard.SidebarGroup")
	proto.RegisterType((*SidebarEntry)(nil), "dashboard.SidebarEntry")
	proto.RegisterType((*GetSidebarMenusReq)(nil), "dashboard.GetSidebarMenusReq")
	proto.RegisterType((*GetSidebarMenusRes)(nil), "dashboard.GetSidebarMenusRes")
	proto.RegisterType((*Result)(nil), "dashboard.Result")
	proto.RegisterType((*YsadminReq)(nil), "dashboard.YsadminReq")
	proto.RegisterType((*QueryReq)(nil), "dashboard.QueryReq")
	proto.RegisterType((*QueryRes)(nil), "dashboard.QueryRes")
	proto.RegisterType((*CommitReq)(nil), "dashboard.CommitReq")
	proto.RegisterType((*CommitRes)(nil), "dashboard.CommitRes")
	proto.RegisterType((*TdInfo)(nil), "dashboard.TdInfo")
	proto.RegisterType((*TdRow)(nil), "dashboard.TdRow")
	proto.RegisterType((*TableInfo)(nil), "dashboard.TableInfo")
	proto.RegisterType((*ChartInfo)(nil), "dashboard.ChartInfo")
	proto.RegisterType((*Dataset)(nil), "dashboard.Dataset")
}

func init() { proto.RegisterFile("dashboard.proto", fileDescriptor_9b97678da3a35dfb) }

var fileDescriptor_9b97678da3a35dfb = []byte{
	// 1296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x25, 0x91, 0xb2, 0x46, 0x8e, 0xcd, 0x6c, 0x5c, 0x9b, 0x75, 0x13, 0xd4, 0x21, 0x0a,
	0x24, 0x31, 0xd2, 0xb4, 0x70, 0x80, 0xa0, 0xe8, 0x4d, 0x3f, 0xac, 0x22, 0x54, 0xa6, 0x9c, 0x35,
	0x93, 0xd4, 0xbd, 0x10, 0xb4, 0xb8, 0x96, 0x58, 0x4b, 0xa4, 0x42, 0xae, 0xa2, 0x08, 0x7d, 0x82,
	0x9e, 0xfa, 0x02, 0xbd, 0x15, 0x7d, 0x8c, 0x3e, 0x4a, 0x5f, 0xa2, 0xb7, 0xde, 0x8a, 0x9d, 0xe5,
	0x9f, 0x6a, 0x27, 0x68, 0x7b, 0xe2, 0xcc, 0x37, 0xdf, 0xce, 0xce, 0xce, 0xcf, 0x72, 0x61, 0xc7,
	0xf7, 0x92, 0xc9, 0x45, 0xe4, 0xc5, 0xfe, 0x93, 0x79, 0x1c, 0xf1, 0x88, 0x34, 0x72, 0xc0, 0xbc,
	0x0f, 0xea, 0x73, 0x36, 0x9d, 0x46, 0xc4, 0x80, 0xfa, 0x8c, 0x25, 0x89, 0x37, 0x66, 0x86, 0x72,
	0xa8, 0x3c, 0x6c, 0xd0, 0x4c, 0x35, 0xef, 0x42, 0xed, 0x34, 0x0a, 0xc7, 0x64, 0x17, 0xd4, 0x98,
	0xcd, 0xa7, 0xab, 0xd4, 0x2e, 0x15, 0xf3, 0x47, 0x68, 0x9e, 0x05, 0x3e, 0xbb, 0xf0, 0xe2, 0x13,
	0x16, 0x2e, 0xc8, 0x36, 0x54, 0x02, 0x3f, 0x65, 0x54, 0x02, 0x9f, 0xec, 0x43, 0xfd, 0xd2, 0x73,
	0x83, 0x51, 0x14, 0x1a, 0x15, 0x04, 0xb5, 0x4b, 0xaf, 0x3f, 0x8a, 0x42, 0x42, 0xa0, 0xc6, 0xd9,
	0x3b, 0x6e, 0x54, 0x11, 0x45, 0x99, 0x7c, 0x01, 0xda, 0x38, 0x8e, 0x16, 0xf3, 0xc4, 0xa8, 0x1d,
	0x56, 0x1f, 0x36, 0x8f, 0xf7, 0x9f, 0x14, 0x91, 0xa7, 0x9b, 0xf4, 0x84, 0x9d, 0xa6, 0x34, 0xf3,
	0x05, 0x6c, 0x95, 0xf1, 0xdc, 0xa9, 0x52, 0x72, 0xfa, 0x39, 0xa8, 0x01, 0x67, 0xb3, 0xc4, 0xa8,
	0xbc, 0xcf, 0xa7, 0x15, 0xf2, 0x78, 0x45, 0x25, 0xcb, 0xfc, 0x2a, 0x77, 0x89, 0xf0, 0x8d, 0x2e,
	0x45, 0x26, 0xa2, 0x05, 0x67, 0xe9, 0x91, 0xa4, 0x62, 0xee, 0x02, 0xe9, 0x31, 0x5e, 0x4a, 0x46,
	0x42, 0xd9, 0x1b, 0xb3, 0x7d, 0x03, 0x9a, 0x90, 0xc7, 0xa0, 0xce, 0x84, 0x6c, 0x28, 0x18, 0xd4,
	0xde, 0xf5, 0xa0, 0x04, 0x95, 0x4a, 0x92, 0xf9, 0x35, 0x68, 0x94, 0x25, 0x8b, 0x29, 0x17, 0x55,
	0x62, 0x71, 0x3c, 0x8a, 0x7c, 0x59, 0xa5, 0x2a, 0xcd, 0x54, 0xb2, 0x07, 0x1a, 0x8b, 0xe3, 0x59,
	0x32, 0xce, 0xf2, 0x2c, 0x35, 0xf3, 0xaf, 0x0a, 0xc0, 0x79, 0xe2, 0xf9, 0xb3, 0x20, 0xa4, 0xec,
	0x0d, 0xd1, 0xa1, 0x3a, 0x9a, 0x65, 0x05, 0x12, 0xa2, 0x40, 0x16, 0x81, 0x8f, 0xab, 0xaa, 0x54,
	0x88, 0xe2, 0xc8, 0xbe, 0xc7, 0x59, 0x56, 0x1a, 0x21, 0x93, 0x7b, 0x00, 0x09, 0xf7, 0x62, 0xee,
	0xa2, 0xa5, 0x86, 0x96, 0x06, 0x22, 0x5d, 0x61, 0xfe, 0x18, 0x36, 0x59, 0xe8, 0x4b, 0xa3, 0x2a,
	0xdb, 0x87, 0x85, 0x3e, 0x9a, 0x44, 0x60, 0xef, 0xe6, 0x5e, 0xe8, 0x1b, 0x5a, 0x1a, 0x18, 0x6a,
	0x22, 0x89, 0x3c, 0xba, 0x62, 0xa1, 0x51, 0x97, 0x49, 0x44, 0x45, 0xa0, 0x49, 0xe8, 0xcd, 0x98,
	0xb1, 0x29, 0x51, 0x54, 0x30, 0xea, 0xc0, 0x37, 0x1a, 0x69, 0xd4, 0x01, 0xae, 0x9e, 0x45, 0x21,
	0x9f, 0x18, 0x20, 0x79, 0xa8, 0x88, 0xc8, 0x97, 0x8c, 0x5d, 0x19, 0x4d, 0x19, 0xb9, 0x90, 0x05,
	0x36, 0x17, 0x5d, 0xbd, 0x75, 0xa8, 0x3c, 0x54, 0x29, 0xca, 0x22, 0xa6, 0x98, 0x8d, 0x83, 0x28,
	0x34, 0x6e, 0xc9, 0x98, 0xa4, 0x26, 0xd2, 0x3b, 0x8a, 0x16, 0xa2, 0xee, 0xc6, 0xb6, 0x3c, 0x45,
	0xaa, 0x0a, 0x2f, 0x5e, 0xcc, 0x3c, 0x63, 0x47, 0x7a, 0x16, 0x32, 0xf9, 0x14, 0x9a, 0xa3, 0x69,
	0x30, 0xba, 0x72, 0xdf, 0x7a, 0xd3, 0x05, 0x33, 0x76, 0xd1, 0x04, 0x08, 0xbd, 0x12, 0x88, 0xf9,
	0xbb, 0x02, 0x9b, 0x2f, 0x16, 0x2c, 0x5e, 0x89, 0xcc, 0x1b, 0x50, 0x9f, 0x7b, 0xa3, 0xab, 0xd2,
	0x80, 0xa5, 0x2a, 0x39, 0xc0, 0xe4, 0xcd, 0xa3, 0x20, 0xe4, 0x69, 0xf1, 0x72, 0x9d, 0x1c, 0x42,
	0x93, 0x85, 0x6f, 0x83, 0x38, 0x0a, 0x67, 0x2c, 0xcc, 0xa6, 0xa5, 0x0c, 0x91, 0xfb, 0xb0, 0x35,
	0xf6, 0x38, 0x5b, 0x7a, 0x2b, 0x17, 0xfb, 0x42, 0xd6, 0xa6, 0x99, 0x62, 0x1d, 0xd1, 0x1b, 0xcf,
	0xa0, 0xb9, 0x92, 0x2d, 0xe0, 0xc6, 0xec, 0x0d, 0x16, 0xa8, 0x79, 0xfc, 0x51, 0xa9, 0xe7, 0x8a,
	0x06, 0xa1, 0xb0, 0xca, 0x65, 0xf3, 0xb7, 0x22, 0xfe, 0x84, 0x3c, 0x12, 0x39, 0x13, 0x4d, 0x88,
	0xe1, 0x37, 0x8f, 0x6f, 0x97, 0xd6, 0xcb, 0xee, 0xa4, 0x29, 0x81, 0x3c, 0x06, 0x8d, 0x7b, 0x17,
	0x53, 0x96, 0xcd, 0xdc, 0x6e, 0x89, 0xea, 0x08, 0x43, 0x3f, 0xbc, 0x8c, 0x68, 0xca, 0x11, 0xec,
	0xd1, 0xc4, 0x8b, 0x79, 0x62, 0x54, 0xaf, 0xb1, 0x3b, 0xc2, 0x20, 0xd9, 0x92, 0x93, 0x97, 0xb3,
	0x56, 0x94, 0xd3, 0xfc, 0x01, 0x1a, 0x9d, 0x68, 0x36, 0x0b, 0xf8, 0xff, 0xcf, 0xf3, 0x03, 0xa8,
	0x8a, 0xd4, 0x54, 0x3f, 0x94, 0x1a, 0xc1, 0x30, 0x9f, 0x15, 0x7b, 0xfd, 0x97, 0x9c, 0x98, 0x3f,
	0x55, 0x40, 0x73, 0x7c, 0x71, 0x14, 0x72, 0x04, 0x75, 0xee, 0xbb, 0x7c, 0x35, 0x97, 0x11, 0x6e,
	0xaf, 0x2d, 0x73, 0x7c, 0x67, 0x35, 0x67, 0x54, 0xe3, 0xf8, 0x95, 0x1d, 0x19, 0x72, 0x96, 0x87,
	0x9c, 0xa9, 0xe2, 0x66, 0x0d, 0x12, 0x97, 0xc7, 0x0b, 0x39, 0xa8, 0x9b, 0x54, 0x0b, 0x12, 0x27,
	0x5e, 0x30, 0x91, 0xa1, 0x69, 0x10, 0x5e, 0xa5, 0x8d, 0x80, 0x32, 0x39, 0x02, 0x75, 0x14, 0x4d,
	0xa3, 0x18, 0x6b, 0xbf, 0xbd, 0x9e, 0x62, 0x81, 0xe3, 0x9e, 0x92, 0x22, 0x46, 0x6b, 0x19, 0xf8,
	0x7c, 0x82, 0xf3, 0xaa, 0x52, 0xa9, 0x88, 0x91, 0x99, 0xb0, 0x60, 0x3c, 0xe1, 0x38, 0xaf, 0x2a,
	0x4d, 0x35, 0x1c, 0xe3, 0x80, 0x4f, 0xf3, 0x81, 0x45, 0x85, 0xdc, 0x85, 0x06, 0xce, 0x81, 0xa8,
	0x30, 0x8e, 0xed, 0x26, 0x2d, 0x00, 0xf3, 0x4b, 0x50, 0x1d, 0x9f, 0x46, 0x4b, 0xf2, 0x00, 0xd4,
	0x20, 0xbc, 0x8c, 0xb2, 0x6b, 0x70, 0x3d, 0x0f, 0x58, 0x76, 0x69, 0x37, 0x5f, 0x43, 0x23, 0x6f,
	0x1c, 0x71, 0x40, 0xbc, 0x22, 0xd2, 0x2b, 0x39, 0xbb, 0x21, 0xf8, 0x44, 0xf6, 0x5b, 0x83, 0x0a,
	0x91, 0x7c, 0x06, 0xb5, 0x38, 0x5a, 0x66, 0x4d, 0xa5, 0xaf, 0xb9, 0xa6, 0xd1, 0x92, 0xa2, 0xd5,
	0xfc, 0x45, 0x81, 0x46, 0xde, 0x64, 0xe4, 0x29, 0x00, 0xb6, 0x59, 0xb9, 0x38, 0xd7, 0xda, 0x11,
	0x73, 0xd5, 0x18, 0x65, 0x62, 0x1e, 0x4e, 0xa5, 0x14, 0xce, 0x1e, 0x68, 0x53, 0xef, 0x82, 0x4d,
	0xe5, 0xf6, 0x0d, 0x9a, 0x6a, 0xe4, 0x09, 0x6c, 0xfa, 0x1e, 0xf7, 0x12, 0xc6, 0xb3, 0x7f, 0x1c,
	0x29, 0xb9, 0xef, 0x4a, 0x13, 0xcd, 0x39, 0xe6, 0xcf, 0x0a, 0xd4, 0x53, 0x54, 0x64, 0x1a, 0xbd,
	0x64, 0xff, 0x5f, 0x54, 0x8a, 0xca, 0x56, 0xfe, 0x55, 0x65, 0xd1, 0x33, 0x06, 0x55, 0xa5, 0x52,
	0xc1, 0xf9, 0x13, 0x66, 0x19, 0xd1, 0xfb, 0x5c, 0xa4, 0x9c, 0xa3, 0x5f, 0x15, 0xd1, 0xc7, 0x78,
	0xf0, 0x1d, 0x68, 0x3a, 0x5d, 0xe7, 0xfc, 0xd4, 0x72, 0x1d, 0xeb, 0x3b, 0x47, 0xdf, 0x20, 0x3a,
	0x6c, 0xa5, 0x40, 0xbb, 0xd5, 0xed, 0x59, 0xba, 0x52, 0xa2, 0xb4, 0x87, 0xc3, 0x81, 0x5e, 0x21,
	0xdb, 0x00, 0x29, 0xd0, 0x3f, 0xe9, 0xe9, 0xd5, 0x12, 0x61, 0xd0, 0xb7, 0xbf, 0xd5, 0x6b, 0xe4,
	0x36, 0xdc, 0x4a, 0x81, 0xd6, 0xab, 0x96, 0xd3, 0xa2, 0xba, 0x4a, 0xee, 0xc0, 0x4e, 0xb1, 0x46,
	0xee, 0xa5, 0x91, 0xbb, 0x60, 0x94, 0xc1, 0xbe, 0x33, 0xb0, 0xdc, 0xce, 0xd0, 0x76, 0x2c, 0xdb,
	0xd1, 0xeb, 0x47, 0x7f, 0x88, 0xb2, 0x66, 0xb1, 0x13, 0x02, 0xdb, 0x9d, 0xe1, 0x60, 0x48, 0x91,
	0x6e, 0x0f, 0x6d, 0x4b, 0xdf, 0x20, 0x9f, 0xc0, 0x7e, 0x81, 0xf5, 0xa8, 0x65, 0xd9, 0xee, 0xd9,
	0xcb, 0x4e, 0xc7, 0x3a, 0x3b, 0xd3, 0x15, 0x72, 0x00, 0x7b, 0x85, 0xb1, 0x3d, 0x78, 0x69, 0xb9,
	0xa7, 0xb4, 0x7f, 0xd2, 0xa2, 0xe7, 0x7a, 0x85, 0x18, 0xb0, 0x5b, 0xd8, 0xa8, 0xd5, 0x75, 0xbb,
	0x2d, 0xbb, 0x67, 0x51, 0xbd, 0x2a, 0x42, 0x2a, 0x2c, 0xe7, 0xd6, 0x60, 0x30, 0x7c, 0xed, 0xbe,
	0x6e, 0x51, 0xbb, 0x6f, 0xf7, 0xf4, 0x1a, 0xd9, 0x87, 0x3b, 0x85, 0xb5, 0x73, 0xde, 0xb2, 0xdd,
	0xbe, 0xfd, 0xcd, 0x50, 0x57, 0xd7, 0x97, 0xf5, 0x68, 0xeb, 0xdc, 0x3d, 0xb3, 0x3a, 0x43, 0xbb,
	0x2b, 0xb6, 0xd3, 0xc8, 0x2e, 0xe8, 0xa5, 0xed, 0x5a, 0x76, 0x77, 0x78, 0xa2, 0xd7, 0x8f, 0xac,
	0xb4, 0x6b, 0xf3, 0xe3, 0x3d, 0x6f, 0x51, 0x27, 0x4b, 0xa3, 0x38, 0xde, 0x6d, 0xb8, 0x55, 0x60,
	0xed, 0x16, 0xd5, 0x95, 0x75, 0xe8, 0xb4, 0x6f, 0xe9, 0x95, 0xe3, 0x3f, 0x15, 0xa8, 0xb7, 0xbd,
	0xd1, 0x15, 0x0b, 0x7d, 0xf2, 0x08, 0x6a, 0xa7, 0x41, 0x38, 0x26, 0xe5, 0x49, 0xc1, 0xa7, 0xe1,
	0xc1, 0x4e, 0x09, 0xc1, 0x97, 0xe0, 0x10, 0x76, 0xfe, 0xf1, 0xa6, 0x21, 0xf7, 0x4a, 0x9c, 0xeb,
	0xaf, 0xa0, 0x83, 0x0f, 0x9a, 0x13, 0xf2, 0x14, 0x54, 0xfc, 0xcf, 0x90, 0x3b, 0x25, 0x5e, 0xf6,
	0xe7, 0x3c, 0xb8, 0x01, 0x4c, 0xcc, 0x0d, 0xf2, 0x0c, 0x34, 0x79, 0x13, 0x93, 0xf5, 0x8e, 0x4d,
	0x7f, 0x04, 0x07, 0x37, 0xa1, 0x89, 0xb9, 0xd1, 0x6e, 0x7e, 0x5f, 0xbc, 0x7f, 0x2f, 0x34, 0x7c,
	0x11, 0x3f, 0xfd, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x44, 0x38, 0xf2, 0x24, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendClient interface {
	Ping(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Pong, error)
	GetSidebarMenus(ctx context.Context, in *GetSidebarMenusReq, opts ...grpc.CallOption) (*GetSidebarMenusRes, error)
	// --- ysadmin.proto
	Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryRes, error)
	Commit(ctx context.Context, in *CommitReq, opts ...grpc.CallOption) (*CommitRes, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) Ping(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/dashboard.Backend/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetSidebarMenus(ctx context.Context, in *GetSidebarMenusReq, opts ...grpc.CallOption) (*GetSidebarMenusRes, error) {
	out := new(GetSidebarMenusRes)
	err := c.cc.Invoke(ctx, "/dashboard.Backend/GetSidebarMenus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryRes, error) {
	out := new(QueryRes)
	err := c.cc.Invoke(ctx, "/dashboard.Backend/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Commit(ctx context.Context, in *CommitReq, opts ...grpc.CallOption) (*CommitRes, error) {
	out := new(CommitRes)
	err := c.cc.Invoke(ctx, "/dashboard.Backend/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
type BackendServer interface {
	Ping(context.Context, *Hello) (*Pong, error)
	GetSidebarMenus(context.Context, *GetSidebarMenusReq) (*GetSidebarMenusRes, error)
	// --- ysadmin.proto
	Query(context.Context, *QueryReq) (*QueryRes, error)
	Commit(context.Context, *CommitReq) (*CommitRes, error)
}

// UnimplementedBackendServer can be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (*UnimplementedBackendServer) Ping(ctx context.Context, req *Hello) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedBackendServer) GetSidebarMenus(ctx context.Context, req *GetSidebarMenusReq) (*GetSidebarMenusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSidebarMenus not implemented")
}
func (*UnimplementedBackendServer) Query(ctx context.Context, req *QueryReq) (*QueryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedBackendServer) Commit(ctx context.Context, req *CommitReq) (*CommitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Backend/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Ping(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetSidebarMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSidebarMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetSidebarMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Backend/GetSidebarMenus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetSidebarMenus(ctx, req.(*GetSidebarMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Backend/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Query(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Backend/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Commit(ctx, req.(*CommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Backend_Ping_Handler,
		},
		{
			MethodName: "GetSidebarMenus",
			Handler:    _Backend_GetSidebarMenus_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Backend_Query_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Backend_Commit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}
